name: Generate ASCII

on: push

jobs:
   built_job1:
   runs-on: ubuntu-latest
   steps:
    - name: Install cowsay program
      run: sudo apt-get install cowsay -y

     - name: Execute cowsay CMD
       run: cowsay -f dragon "run for cover, I am Dragon...RAWR" >> dragon.txt

     - name: sleep for 30 seconds
       run: sleep 30  

  test_job2: 
  runs-on: ubuntu-latest
  steps:
    - name: Text file exists
      run: grep -i "dragon" dragon.txt   

    - name: sleep for 10 seconds
      run: 10 seconds

  built_job3:
  runs-on: ubuntu-latest
  steps: 
    - name: Read files
      run: cat dragon.txt

    - name: deploy
      run: echo "deploying...."        
