name: Generate ASCII

on: push

jobs:
  built_job1:
    runs-on: ubuntu-latest
    steps:
    - name: Install cowsay program
      run: sudo apt-get install cowsay -y

    - name: Execute cowsay CMD
      run: cowsay -f dragon "run for cover, I am Dragon...RAWR" >> dragon.txt

    - name: Sleep for 30 seconds
      run: sleep 30  

  test_job2: 
    needs: built_job1
    runs-on: ubuntu-latest
    steps:
    - name: Text file exists
      run: test -f dragon.txt && grep -i "dragon" dragon.txt || echo "File not found"

    - name: Sleep for 10 seconds
      run: sleep 10

  built_job3:
    needs: [test_job2]
    runs-on: ubuntu-latest
    steps: 
    - name: Read files
      run: cat dragon.txt || echo "File not found"

    - name: Deploy
      run: echo "Deploying...."  
      
