name: Generate ASCII

on: push

jobs:
  Generate_ascii:
    runs-on: ubuntu-latest
    steps:

    - name: checkout repo
      uses: actions/checkout@v2

    - name: Execting shell script
      run: |
        chmod +x ascii-script.sh
        ./ascii-script.sh
