name: matric-configuration

on:
  push:
  workflow_dispatch:

jobs:
  deploy-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Echo Docker details on Linux
        run: docker info

      - name: Run Hello World container on Linux
        run: docker run hello-world

  deploy-windows:
    runs-on: windows-latest
    steps:
      - name: Echo Docker details on Windows
        run: docker info

      - name: Run Hello World container on Windows
        run: docker run hello-world
