name: matric-configuration

on:
  push:
  workflow_dispatch:

jobs:
  deploy-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Echo Docker details on Linux
        run: docker info

      - name: Run Hello World container on Linux
        run: docker run hello-world

  deploy-matrix:
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu 20.04,windows-latest]
        image: [hello-world, alpine]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Echo Docker details
        run: docker info

      - name: Run container with image ${{ matrix.os }}
        run: docker run ${{ matrix.image }}
