name: Variable Secrets

on: 
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    concurrency:
     group: production-deployment
     cancel-in-progress: true

    env:
      MY_ENV_VAR: "Hello World"
      API_USERNAME: ${{ vars.API_USERNAME }}
      API_KEY: ${{ secrets.API_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Sleep for 30 seconds
        run: sleep 30

      - name: Print environment variables
        run: |
          echo "The environment variable is: $MY_ENV_VAR"
          echo "The API username is: $API_USERNAME"
          echo "The API key is: $API_KEY"
