name: Variable secrets

on: 
  workflow_dispatch

#push

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      MY_ENV_VAR: "Hello World"
      API_USERNAME: ${{ vars.API_USERNAME }}
      API_KEY: ${{ secrets.API_KEY}}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: sleep for 30 seconds
        run: sleep 30 seconds 

      - name: Print environment variables
        run: |
          echo "The environment variable is: $MY_ENV_VAR"
          echo "The API key is: $API_KEY"
