name: Variable Secrets

on: 
  workflow_dispatch:
  schedule:
    - cron: '*/1 * * * *'

concurrency:
    group: production
    cancel-in-progress: true   

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      MY_ENV_VAR: "Hello World"
      API_USERNAME: ${{ vars.API_USERNAME }}
      API_KEY: ${{ secrets.API_KEY }}

  steps:   
      timeout-minutes: 1
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Sleep for 120 seconds
        run: sleep 120

      - name: Print environment variables
        run: |
          echo "The environment variable is: $MY_ENV_VAR"
          echo "The API username is: $API_USERNAME"
          echo "The API key is: $API_KEY"
