name: Variable Secret

on: push

env:
  CONTAINER_REGISTRY: docker.io
  DOCKER_USERNAME: midhunkumar21
  IMAGE_NAME: github-action-nginx

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2  # Ensure repository is checked out

    - name: List Files in the Repository
      run: ls -la  # Verify that Dockerfile is in the root directory

    - name: Docker Build
      run: docker build -t ${{ env.CONTAINER_REGISTRY }}/$DOCKER_USERNAME/$IMAGE_NAME:latest .

    - name: Docker Login
      env: 
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: docker login --username=$DOCKER_USERNAME --password=$DOCKER_PASSWORD

    - name: Docker Push
      run: docker push ${{ env.CONTAINER_REGISTRY }}/$DOCKER_USERNAME/$IMAGE_NAME:latest

  deploy:
    needs: docker
    runs-on: ubuntu-latest
    steps:
    - name: Docker Run
      run: docker run -d -p 8080:80 ${{ env.CONTAINER_REGISTRY }}/$DOCKER_USERNAME/$IMAGE_NAME:latest
