name: Variable Secrets

on: push

env:
 CONTAINER REGISREY: docker.io
 DOCKER USERNAME: Midhunkumar21
 IMAGE NAME: github-action-nginx

Jobs:
 docker:
   runs_on: ubuntu-latest
   steps:
    - name: docker built
      run: docker built -t $env.CONTAINER REGISTERY/$DOCKER USERNAME/$IMAGE NAME : latest

    - name: docker login
      run: docker login --username Midhunkumar21 --password MITHUNmithun01@

    - name: docker push
      run: docker push $CONTAINER REGISTRY/$DOCKER USERNAME/$IMAGE NAME : latest

  deploy:
    runs_on: ubuntu-latest
    steps:
     - name: docker run
       run: docker run -d 8080:80 $CONTAINER REGISTRY/$DOCKER USERNAME/$IMAGE NAME: latest
            
